if: tag IS present
os: linux
dist: bionic
language: shell
addons:
  apt:
    packages:
      - qemu-utils
script:
  - chmod +x ./build.sh
  - ./build.sh
deploy:
  provider: releases
  edge: true
  token:
    secure: FCx3rVwdc+a63zQNeh56cLXXcy7+gC7KebADwx2w8eiLox6t0G5UpSox6HWuKGiGlyH0pTVAK6Oe6qcKVoO/UFCrxOI/GgK1rXwHuseDZtcHcgWkDO8sLSNcfA6mKvzQf9uBcTb+pKxydc8Cv0/pGkq61+YdOpiGxyoFyj7FFC0/9QPLo2GpnzG2oiQAqAni9jxThkHUJpGlZakpAeVYZKS6kOrnhdo0+i9E4TGvUmsfkp6/6zIY/QLo5PF7hHxAdPZDd8I/hn5UWgchnaWdXYDQ0I+UqR7CDGcBtBWPLK5XkzNVTaXV/ed3sKymYkw/ZvXJbZIIqnQAqfcKKilEPHGWpZPBmhMmsDhTflEwgVL+qo76AwOaRjCcRqtP1sAh8cBwzcn4pPZqkDO5rqnVO0J08/fUfnMvCvTcFXvy3voHz6Kg/78hHfnAZAdUwhzJqsYO3v79NFVNvRmbgP7+LjdHPiiYihszrreHJoJWDuMv7dcgFtpEqYk+U4/0duDa53eg7EmUKTyMJ3t+VA5V2cbWG1DFQsbvhm9273Mgs5C9lh0NgKBnA7qLjX5wnWuskA7iszS7gvoVgswCPix2PVe61GxUIAt63/uUANfUzMnWj0Yxv7VG9fkomsqq9UeY3vRadcK7kg0lOlnbXMlojKnTZQVp+o6JTF/0G1GxRr8=
  file: 'wsl/dist/*.zip'
  on:
    repo: mishamosher/CentOS-WSL
    tags: true
    all_branches: true
