if: tag IS present
os: linux
dist: bionic
language: shell
addons:
  apt:
    packages:
      - qemu-utils
script:
  - chmod +x ./build.sh
  - ./build.sh
deploy:
  provider: releases
  edge: true
  token:
    secure: Bx2RYtoHCovLUzDtDgcG19PnQw9svnmlJzGjjyXQ8VbNMv6eutk6N6Q03wXcM8Bv0t45y9TPMV0e1BEwof8D+jkwLKgNALgvGsddMguLOFseqjkXiAJNQC72WEUOG5+sc3+wiMZCrYn2j4c43gwp9CyfFS6XNzNlLddhLTYAwW53yTCOE+NYhCEn/fGEujZPFbOfYOVelouuw0iZaDAtKhX6cYvpdwldENh2fcZovVPEB2E5+8smH/tRfBrbFFGQNrUuIdODzR82uzdbZJFPdi216WwydkkH05fmo6Ndu++GQjCavIrvea5mKC/29wATfsIdWrXWuSBC4CPqPSQDYnCT4Fhy1v5Td1o82zVKJZcPYK6hTuQiK93b8nEZLExivWTgoOVQ2FCVnZzn3xNZSO1G4bpPfZ2UYn9V9iB2Wc2m3v0QHdP/p8SSFx6w3pZts82uZMZcOKPmeleTF64uOAqQX+F8Id+lO+aNVu9zbGOCZhdESHav0CkwHQnrYEpMmEGy/k7K3hlUyjdIMXgazM5HweASo3qGXA0Y/OV0VnCOPso5HjvWWEl9rCAqWvDzRdc23MIX68MX14+mcyVs2GQzwWAh+d+kVvhJKizT1CVbQUsnhq5FK3ESIzdiylUMysi8/uX3xZVYnfOCgEk3vMYpSkJZ7rQao0hJPKeIQvA=
  file: 'wsl/dist/*.zip'
  on:
    repo: mishamosher/CentOS-WSL
    tags: true
    all_branches: true
