name: CI 9-stream

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install qemu-utils

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          chmod +x ./build.sh
          ./build.sh
